# Generated by Django 5.2.16 on 2026-08-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_more_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('code', 'Code / Development'), ('cloud', 'Cloud / IT Services'), ('cart', 'E-commerce / Retail'), ('shield', 'Security / Consulting'), ('chart', 'Data / Analytics'), ('devices', 'Devices / Integration'), ('globe', 'Website / Web'), ('support', 'Technical Support')], default='code', max_length=20),
        ),
    ]
