# Generated by Django 5.2.16 on 2026-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_website_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('website_type', models.CharField(choices=[('business', 'Business / corporate website'), ('ecommerce', 'Online store (e-commerce)'), ('portfolio', 'Portfolio / personal website'), ('landing', 'Landing page for a campaign or product'), ('webapp', 'Web application / custom system'), ('other', 'Something else')], max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('under_5k', 'Under 5,000 QAR'), ('5k_15k', '5,000 – 15,000 QAR'), ('15k_30k', '15,000 – 30,000 QAR'), ('30k_plus', '30,000+ QAR')], max_length=20)),
                ('timeline', models.CharField(choices=[('asap', 'As soon as possible'), ('1_month', 'Within a month'), ('1_3_months', '1–3 months'), ('flexible', 'Flexible / just exploring')], max_length=20)),
                ('features', models.CharField(blank=True, max_length=255)),
                ('reference_sites', models.CharField(blank=True, max_length=500)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
