# Generated by Django 5.2.16 on 2026-09-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_websiterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterequest',
            name='budget_range',
            field=models.CharField(choices=[('under_5k', 'Under 5,000 QAR'), ('5k_15k', '5,000 – 15,000 QAR'), ('15k_30k', '15,000 – 30,000 QAR'), ('30k_plus', '30,000+ QAR')], max_length=20),
        ),
    ]
