# Generated by Django 5.2.16 on 2026-09-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_websiterequest_budget_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='analytics_tools',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='branches_count',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='branches_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='contact_channels',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='contact_channels_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='content_readiness',
            field=models.CharField(choices=[('ready', 'Content is fully ready on our side'), ('need_help', 'We need full help preparing the content'), ('mixed', 'A mix of both')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='has_branches',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='has_brand_identity',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='has_domain_hosting',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='has_existing_system',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='has_specific_date',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='integration_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='language_preference',
            field=models.CharField(choices=[('ar', 'Arabic only'), ('en', 'English only'), ('both', 'Arabic + English')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='legal_requirements',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='needs_domain_hosting_help',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='needs_integration',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='online_services_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='other_goal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='other_legal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='post_launch_control',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='preferred_domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='services_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='success_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='website_goals',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
